# Generated by Django 6.0 on 2026-03-04 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settle_subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
